# 文件名建议统一为 preview-publish
# 应用 preview.yml 的 demo

name: PREVIEW_PUBLISH

on:
  workflow_run:
    workflows: ["MAIN_PULL_REQUEST"]
    types:
      - completed

jobs:
  UPDATE_OFFICIAL_WEBSITE:
    runs-on: ubuntu-latest
    steps:
      - uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
