# 文件名建议统一为 pull-request.yml 
# 应用 test-build.yml 的 demo

name: MAIN_PULL_REQUEST

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: main-comment
        uses: actions-cool/maintain-one-comment@v2.0.0
        with:
          token: ${{ secrets.TOKEN }}
          body: |
            hi
            <!-- AUTO_ASSIGENEES_NOTIFY_HOOK -->
          body-include: "<!-- AUTO_ASSIGENEES_NOTIFY_HOOK -->"